force-app/main/default/objects/CourseEnrollment__c/CourseEnrollment__c.object-meta.xml
<CustomObject>
    <description>Course enrollments for the attendees</description>
    <label>Course Enrollment</label>
    <nameField>
        <displayFormat>E-{0}</displayFormat>
        <label>EnrollmentId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseEnrollment__c/fields/ScheduledCourseId__c.field-meta.xml
<CustomField>
    <fullName>ScheduledCourseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Course</label>
    <referenceTo>ScheduledCourse__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>CourseEnrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/ScheduledCourse__c.object-meta.xml
<CustomObject>
    <description>Training schedule for each course</description>
    <label>Scheduled Course</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>SheduledCourseId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ControllerCourseListAIM.cls
public class ControllerCourseListAIM {
    public List<ScheduledCourse__c> trainings {
        get {
            if (trainings == null){
                trainings = ControllerTrainings.getAllTrainings('AIM');
            }
            return trainings;
        }
        private set;
    }

    public Map<Id,Integer> registeredAttendees {
        get {
            if (registeredAttendees == null){
                registeredAttendees = new Map<Id,Integer>();

                for (ScheduledCourse__c c : trainings){
                    registeredAttendees.put(c.Id, 0);
                }
                List<CourseEnrollment__c> ces = ControllerTrainings.currentRegistrantList(registeredAttendees.keySet());
                for (CourseEnrollment__c c : ces){
                    if (registeredAttendees.containsKey(c.ScheduledCourseId__c)){
                        registeredAttendees.put(c.ScheduledCourseId__c, registeredAttendees.get(c.ScheduledCourseId__c) + 1);
                    } else {
                        registeredAttendees.put(c.ScheduledCourseId__c, 1);
                    }
                }
            }
            return registeredAttendees;
        }
        private set;

    }
}