force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>Training courses</description>
    <label>Course</label>
    <nameField>
        <label>Course System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/CourseName__c.field-meta.xml
<CustomField>
    <fullName>CourseName__c</fullName>
    <label>Course Name</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/CourseType__c.field-meta.xml
<CustomField>
    <fullName>CourseType__c</fullName>
    <label>Course Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AIM</fullName>
            </value>
            <value>
                <fullName>GLAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseEnrollment__c/CourseEnrollment__c.object-meta.xml
<CustomObject>
    <description>Course enrollments for the attendees</description>
    <label>Course Enrollment</label>
    <nameField>
        <displayFormat>E-{0}</displayFormat>
        <label>EnrollmentId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseEnrollment__c/fields/RegistrationStatus__c.field-meta.xml
<CustomField>
    <fullName>RegistrationStatus__c</fullName>
    <label>Registration Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseEnrollment__c/fields/ScheduledCourseId__c.field-meta.xml
<CustomField>
    <fullName>ScheduledCourseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Course</label>
    <referenceTo>ScheduledCourse__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>CourseEnrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CoursePaymentInfo__c/CoursePaymentInfo__c.object-meta.xml
<CustomObject>
    <label>Course Payment Info</label>
    <nameField>
        <displayFormat>CPI-{00000}</displayFormat>
        <label>Course Payment Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Payment Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CoursePaymentInfo__c/fields/BillingFirstName__c.field-meta.xml
<CustomField>
    <fullName>BillingFirstName__c</fullName>
    <label>Billing First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/ScheduledCourse__c.object-meta.xml
<CustomObject>
    <description>Training schedule for each course</description>
    <label>Scheduled Course</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>SheduledCourseId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduledCourse__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Scheduled Courses</relationshipLabel>
    <relationshipName>Scheduled_Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>We can change it to picklist</description>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/PublishedToWeb__c.field-meta.xml
<CustomField>
    <fullName>PublishedToWeb__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Published To Web</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/RegistreeAcknowledgement__c.field-meta.xml
<CustomField>
    <fullName>RegistreeAcknowledgement__c</fullName>
    <label>Registree Acknowledgement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/WebCourseDescription__c.field-meta.xml
<CustomField>
    <fullName>WebCourseDescription__c</fullName>
    <label>Web Course Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/WebCourseName__c.field-meta.xml
<CustomField>
    <fullName>WebCourseName__c</fullName>
    <label>Web Course Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ScheduledCourseDay__c/ScheduledCourseDay__c.object-meta.xml
<CustomObject>
    <description>Schedule days for training course</description>
    <label>Scheduled Course Day</label>
    <nameField>
        <displayFormat>DAY-{0000}</displayFormat>
        <label>ScheduledCourseDay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ScheduledCourseDays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduledCourseDay__c/fields/ScheduledCourseId__c.field-meta.xml
<CustomField>
    <fullName>ScheduledCourseId__c</fullName>
    <label>Scheduled Course</label>
    <referenceTo>ScheduledCourse__c</referenceTo>
    <relationshipLabel>ScheduledCourseDays</relationshipLabel>
    <relationshipName>ScheduledCourseDays</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScheduledCourseDay__c/fields/ScheduledDate__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDate__c</fullName>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ControllerTrainingsTest.cls
@isTest
public class ControllerTrainingsTest {
    static Map<String,String> mockData;
    static CourseEnrollment__c mockCE;

    @isTest
    public static void getFieldInfo(){
        ControllerTrainings.getFieldInfo();
    }

    @isTest
    public static void getTrainings(){
        Map<String,String> retMap = insertMockData();
        List<ScheduledCourse__c> lst = ControllerTrainings.getAllTrainings('AIM');
        ControllerTrainings.getScheduledCourseInfo(retMap.get('sc'));
    }

    @isTest
    public static void getCurrentRegistrantCount(){
        Map<String,String> retMap = insertMockData();
        List<ScheduledCourse__c> lst = ControllerTrainings.getAllTrainings('AIM');
        ControllerTrainings.currentRegistrantCount(retMap.get('sc'));
    }

    @isTest
    public static void getRosterList(){
        Map<String,String> retMap = insertMockData();
        List<ScheduledCourse__c> lst = ControllerTrainings.getAllTrainings('AIM');
        ControllerTrainings.getRosterList(retMap.get('scd'));
    }

    @isTest
    public static void testMarkingAttended(){
        insertRegistration();
        List<ScheduledCourse__c> lst = ControllerTrainings.getAllTrainings('AIM');
		List<Attendee> attendees = (List<Attendee>)JSON.deserializeStrict(ControllerTrainings.getRosterList(mockData.get('scd')), List<Attendee>.class);
        ControllerTrainings.updateAttendance(attendees[0].Id, true);
        ControllerTrainings.updateNotesText(attendees[0].Id, 'testing');
    }

    @isTest
    public static void insertRegistration(){
        Map<String,String> retMap = insertMockData();
        List<Lead> l = new List<Lead>();
        // successful insert
        l.add((Lead)JSON.deserializeStrict('{"LeadSource":"Web","Lead_Type__c":"AIM4SCubed","FirstName":"first","LastName":"last","Email":"email@email.com","Company":"company"}', Lead.class));
        mockCE = (CourseEnrollment__c)JSON.deserializeStrict('{"ScheduledCourseId__c":"' + retMap.get('sc') + '"}', CourseEnrollment__c.class);
        CoursePaymentInfo__c cpi = (CoursePaymentInfo__c)JSON.deserializeStrict('{"BillingFirstName__c":"first"}', CoursePaymentInfo__c.class);
        ControllerTrainings.submitRegistration(l, mockCE, cpi);

        // fail insert by not providing a last name
        try {
            l[0] = ((Lead)JSON.deserializeStrict('{"LeadSource":"Web","Lead_Type__c":"AIM4SCubed","FirstName":"first","Company":"company"}', Lead.class));
            mockCE = (CourseEnrollment__c)JSON.deserializeStrict('{"ScheduledCourseId__c":"' + retMap.get('sc') + '"}', CourseEnrollment__c.class);
            cpi = (CoursePaymentInfo__c)JSON.deserializeStrict('{"BillingFirstName__c":"first"}', CoursePaymentInfo__c.class);
            ControllerTrainings.submitRegistration(l, mockCE, cpi);
        }
        catch(Exception ex){
            System.assert(ex.getMessage().startsWithIgnoreCase('Error creating registration.'));
        }
    }

    @isTest
    public static void testLeadConversionTrigger(){
        Map<String,String> retMap = insertMockData();
        List<Lead> l = new List<Lead>();
        // successful insert
        l.add((Lead)JSON.deserializeStrict('{"LeadSource":"Web","Lead_Type__c":"AIM4SCubed","FirstName":"first","LastName":"last","Email":"email@email.com","Company":"company"}', Lead.class));
        CourseEnrollment__c ce = (CourseEnrollment__c)JSON.deserializeStrict('{"ScheduledCourseId__c":"' + retMap.get('sc') + '","RegistrationStatus__c":"Registered"}', CourseEnrollment__c.class);
        CoursePaymentInfo__c cpi = (CoursePaymentInfo__c)JSON.deserializeStrict('{"BillingFirstName__c":"first"}', CoursePaymentInfo__c.class);
        ControllerTrainings.submitRegistration(l, ce, cpi);

        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(l[0].Id);

        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);

        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());
    }

    public static Map<String,String> insertMockData(){
        Course__c c = (Course__c)JSON.deserializeStrict('{"Name":"AIM Level 1","CourseName__c":"CourseName","CourseType__c":"AIM"}', Course__c.class);
        insert c;
        ScheduledCourse__c sc = (ScheduledCourse__c)JSON.deserializeStrict('{"CourseId__c" : "' + c.Id + '", "WebCourseDescription__c" : "description", "Location__c" : "location", "WebCourseName__c" : "courseName", "Cost__c" : 1000.00, "RegistreeAcknowledgement__c" : "acknowledgement", "PublishedToWeb__c" : true}', ScheduledCourse__c.class);
        insert sc;
        ScheduledCourseDay__c scd = (ScheduledCourseDay__c)JSON.deserializeStrict('{"ScheduledCourseId__c" : "' + sc.Id + '", "Name" : "Day1", "ScheduledDate__c" : "2018-01-10" }', ScheduledCourseDay__c.class);
        insert scd;

        mockData = new Map<String,String>();
        mockData.put('c',c.Id);
        mockData.put('sc',sc.Id);
        mockData.put('scd',scd.Id);
        return mockData;
    }
}