force-app/main/default/objects/Contact/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>K - 5</fullName>
            </value>
            <value>
                <fullName>K - 12</fullName>
            </value>
            <value>
                <fullName>1st</fullName>
            </value>
            <value>
                <fullName>2nd</fullName>
            </value>
            <value>
                <fullName>3rd</fullName>
            </value>
            <value>
                <fullName>4th</fullName>
            </value>
            <value>
                <fullName>5th</fullName>
            </value>
            <value>
                <fullName>6th - 8th</fullName>
            </value>
            <value>
                <fullName>9th - 12th</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ProgramType__c.field-meta.xml
<CustomField>
    <fullName>ProgramType__c</fullName>
    <label>Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bilingual Maintenance</fullName>
            </value>
            <value>
                <fullName>Dual Language</fullName>
            </value>
            <value>
                <fullName>Structured English Immersion (most other programs)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Classroom Teacher</fullName>
            </value>
            <value>
                <fullName>Special Education Teacher</fullName>
            </value>
            <value>
                <fullName>Instructional Coach/Specialist</fullName>
            </value>
            <value>
                <fullName>School Site Administrator</fullName>
            </value>
            <value>
                <fullName>District Administrator</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>Training courses</description>
    <label>Course</label>
    <nameField>
        <label>Course System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/CourseName__c.field-meta.xml
<CustomField>
    <fullName>CourseName__c</fullName>
    <label>Course Name</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/CourseType__c.field-meta.xml
<CustomField>
    <fullName>CourseType__c</fullName>
    <label>Course Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AIM</fullName>
            </value>
            <value>
                <fullName>GLAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseAttendance__c/CourseAttendance__c.object-meta.xml
<CustomObject>
    <description>Tracks attendance for the students of a course</description>
    <label>Course Attendance</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Attendence Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseAttendance__c/fields/AttendanceNotes__c.field-meta.xml
<CustomField>
    <fullName>AttendanceNotes__c</fullName>
    <label>Attendance Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CourseAttendance__c/fields/Attended__c.field-meta.xml
<CustomField>
    <fullName>Attended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CourseAttendance__c/fields/CourseAttendeeEnrollmentId__c.field-meta.xml
<CustomField>
    <fullName>CourseAttendeeEnrollmentId__c</fullName>
    <label>Course Attendee Enrollment</label>
    <referenceTo>CourseEnrollment__c</referenceTo>
    <relationshipLabel>Course Attendance</relationshipLabel>
    <relationshipName>Course_Attendance</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CourseAttendance__c/fields/ScheduledCourseDayId__c.field-meta.xml
<CustomField>
    <fullName>ScheduledCourseDayId__c</fullName>
    <label>Scheduled Course Day</label>
    <referenceTo>ScheduledCourseDay__c</referenceTo>
    <relationshipLabel>Course Attendance</relationshipLabel>
    <relationshipName>Course_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CourseAttendance__c/fields/ScheduledDate__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDate__c</fullName>
    <formula>DATETIMEVALUE( ScheduledCourseDayId__r.ScheduledDate__c )</formula>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CourseEnrollment__c/CourseEnrollment__c.object-meta.xml
<CustomObject>
    <description>Course enrollments for the attendees</description>
    <label>Course Enrollment</label>
    <nameField>
        <displayFormat>E-{0}</displayFormat>
        <label>EnrollmentId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseEnrollment__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>CourseEnrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseEnrollment__c/fields/CoursePaymentInfoId__c.field-meta.xml
<CustomField>
    <fullName>CoursePaymentInfoId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Payment Info</label>
    <referenceTo>CoursePaymentInfo__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>CourseEnrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseEnrollment__c/fields/LeadId__c.field-meta.xml
<CustomField>
    <fullName>LeadId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>CourseEnrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseEnrollment__c/fields/RegistrationStatus__c.field-meta.xml
<CustomField>
    <fullName>RegistrationStatus__c</fullName>
    <label>Registration Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseEnrollment__c/fields/ScheduledCourseId__c.field-meta.xml
<CustomField>
    <fullName>ScheduledCourseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Course</label>
    <referenceTo>ScheduledCourse__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>CourseEnrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CoursePaymentInfo__c/CoursePaymentInfo__c.object-meta.xml
<CustomObject>
    <label>Course Payment Info</label>
    <nameField>
        <displayFormat>CPI-{00000}</displayFormat>
        <label>Course Payment Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Payment Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/ProgramType__c.field-meta.xml
<CustomField>
    <fullName>ProgramType__c</fullName>
    <label>Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bilingual Maintenance</fullName>
            </value>
            <value>
                <fullName>Dual Language</fullName>
            </value>
            <value>
                <fullName>Structured English Immersion (most other programs)</fullName>
            </value>
            <value>
                <fullName>Special Education</fullName>
                <isActive>false</isActive>
                <label>Special Education</label>
            </value>
            <value>
                <fullName>Structured English Immersion (Title III)</fullName>
                <isActive>false</isActive>
                <label>Structured English Immersion (Title III)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Classroom Teacher</fullName>
            </value>
            <value>
                <fullName>Special Education Teacher</fullName>
            </value>
            <value>
                <fullName>Instructional Coach/Specialist</fullName>
            </value>
            <value>
                <fullName>School Site Administrator</fullName>
            </value>
            <value>
                <fullName>District Administrator</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/ScheduledCourse__c.object-meta.xml
<CustomObject>
    <description>Training schedule for each course</description>
    <label>Scheduled Course</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>SheduledCourseId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduledCourse__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Scheduled Courses</relationshipLabel>
    <relationshipName>Scheduled_Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>We can change it to picklist</description>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/MaxNoRegistrations__c.field-meta.xml
<CustomField>
    <fullName>MaxNoRegistrations__c</fullName>
    <label>Max No Registrations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/PublishedToWeb__c.field-meta.xml
<CustomField>
    <fullName>PublishedToWeb__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Published To Web</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/RegistreeAcknowledgement__c.field-meta.xml
<CustomField>
    <fullName>RegistreeAcknowledgement__c</fullName>
    <label>Registree Acknowledgement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/WebCourseDescription__c.field-meta.xml
<CustomField>
    <fullName>WebCourseDescription__c</fullName>
    <label>Web Course Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/WebCourseName__c.field-meta.xml
<CustomField>
    <fullName>WebCourseName__c</fullName>
    <label>Web Course Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ScheduledCourseDay__c/ScheduledCourseDay__c.object-meta.xml
<CustomObject>
    <description>Schedule days for training course</description>
    <label>Scheduled Course Day</label>
    <nameField>
        <displayFormat>DAY-{0000}</displayFormat>
        <label>ScheduledCourseDay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ScheduledCourseDays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduledCourseDay__c/fields/ScheduledCourseId__c.field-meta.xml
<CustomField>
    <fullName>ScheduledCourseId__c</fullName>
    <label>Scheduled Course</label>
    <referenceTo>ScheduledCourse__c</referenceTo>
    <relationshipLabel>ScheduledCourseDays</relationshipLabel>
    <relationshipName>ScheduledCourseDays</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScheduledCourseDay__c/fields/ScheduledDate__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDate__c</fullName>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ControllerTrainings.cls
public class ControllerTrainings {

    @AuraEnabled
    public static List<ScheduledCourse__c> getAllTrainings(String courseType) {
        return getAllTrainings(courseType, true);
    }

    @AuraEnabled
    public static List<ScheduledCourse__c> getAllTrainings(String courseType, Boolean publishedOnly) {
        List<ScheduledCourse__c> retList = new List<ScheduledCourse__c>();
        List<ScheduledCourse__c> schedCourses = new List<ScheduledCourse__c>();
        if (publishedOnly){
            schedCourses = getPublishedTrainings();
        } else {
            schedCourses = getTrainings();
        }
        for (ScheduledCourse__c c : schedCourses){
        	if (c.CourseId__r.CourseType__c.equalsIgnoreCase(courseType))
                retList.add(c);
        }
        return retList;
    }

    @AuraEnabled
    public static ScheduledCourse__c getScheduledCourseInfo(String scheduledCourseId){
        for (ScheduledCourse__c c : getPublishedTrainings()){
        	if (c.Id.equals(scheduledCourseId))
                return c;
        }
        throw new TrainingClassException('Error finding courseinfo. No course found for :' + scheduledCourseId);
    }

    @AuraEnabled
    public static Integer currentRegistrantCount(String scheduledCourseId){
        Set<Id> cIds = new Set<Id>();
        cIds.add(scheduledCourseId);
        List<CourseEnrollment__c> ces = currentRegistrantList(cIds);
        return ces.size();
    }

    public static List<CourseEnrollment__c> currentRegistrantList(Set<Id> scheduledCourseIds){
        return [select Id, ScheduledCourseId__c from CourseEnrollment__c where RegistrationStatus__c = 'Registered' and ScheduledCourseId__c in: scheduledCourseIds];
    }

    @AuraEnabled
    public static String getRosterList(String scheduledCourseDayId){
        List<Attendee> retList = new List<Attendee>();
        for (CourseAttendance__c ca : [select Id, Attended__c, AttendanceNotes__c, CourseAttendeeEnrollmentId__r.LeadId__r.Name, CourseAttendeeEnrollmentId__r.LeadId__r.Email, CourseAttendeeEnrollmentId__r.ContactId__r.Name, CourseAttendeeEnrollmentId__r.ContactId__r.Email, CourseAttendeeEnrollmentId__r.RegistrationStatus__c from CourseAttendance__c where ScheduledCourseDayId__c =: scheduledCourseDayId and CourseAttendeeEnrollmentId__r.RegistrationStatus__c = 'Registered']){
            retList.add(new Attendee(ca));
        }
        return JSON.serialize(retList);
    }

    @AuraEnabled
    public static void updateAttendance(String caId, Boolean attended){
        CourseAttendance__c ca = new CourseAttendance__c();
        ca.Id = caId;
        ca.Attended__c = attended;
        update ca;
    }

    @AuraEnabled
    public static void updateNotesText(String caId, String notesText){
        CourseAttendance__c ca = new CourseAttendance__c();
        ca.Id = caId;
        ca.AttendanceNotes__c = notesText;
        update ca;
    }

    @AuraEnabled
    public static CoursePaymentInfo__c submitRegistration(List<Lead> l, CourseEnrollment__c ce, CoursePaymentInfo__c cpi){
        try {

            insert l;

            insert cpi;

            List<CourseEnrollment__c> cePerLead = new List<CourseEnrollment__c>();

            // iterate thru all the leads being created
            for (Lead idx : l){
                // copy the CourseEnrollment__c passed in to init a new CourseEnrollment__c
                CourseEnrollment__c newCE = ce.clone(false,false,false,false);
                // set LeadId__c and CoursePaymentInfoId__c for the new CourseEnrollment__c
                newCE.LeadId__c = idx.Id;
                newCE.CoursePaymentInfoId__c = cpi.Id;
                // add to the list of new CourseEnrollment__c to create
                cePerLead.add(newCE);
            }

            insert cePerLead;

            // query out the CPI record to get the reference number
            CoursePaymentInfo__c cpiRet = [select Id, Name from CoursePaymentInfo__c where Id =: cpi.Id];

            return cpiRet;
        }
        catch(Exception ex){
			throw new TrainingClassException('Error creating registration. Error details:' + ex.getMessage() + ex.getStackTraceString());
        }
    }

    @AuraEnabled
    public static Map<String,List<String>> getFieldInfo(){
        Map<String,List<String>> retMap = new Map<String,List<String>>();
        Schema.DescribeFieldResult dfr = null;

        dfr = Lead.Role__c.getDescribe();
		retMap.put('Role__c', new List<String>());
        for (Schema.PicklistEntry v : dfr.getPicklistValues()){
            retMap.get('Role__c').add(v.getLabel());
        }

        dfr = Lead.Grade__c.getDescribe();
		retMap.put('Grade__c', new List<String>());
        for (Schema.PicklistEntry v : dfr.getPicklistValues()){
            retMap.get('Grade__c').add(v.getLabel());
        }

        dfr = Lead.ProgramType__c.getDescribe();
		retMap.put('ProgramType__c', new List<String>());
        for (Schema.PicklistEntry v : dfr.getPicklistValues()){
            retMap.get('ProgramType__c').add(v.getLabel());
        }

        return retMap;
    }

    @testVisible
    private static List<ScheduledCourse__c> getTrainings(){
        return [select Id, Name, CourseId__r.CourseName__c, CourseId__r.CourseType__c, WebCourseDescription__c, Location__c, WebCourseName__c, Cost__c, RegistreeAcknowledgement__c, MaxNoRegistrations__c, PublishedToWeb__c,
                (select Id, Name, ScheduledDate__c from ScheduledCourseDays__r order by ScheduledDate__c)
                from ScheduledCourse__c];
    }

    @testVisible
    private static List<ScheduledCourse__c> getPublishedTrainings(){
        List<ScheduledCourse__c> retList = new List<ScheduledCourse__c>();
        for (ScheduledCourse__c sc : getTrainings()){
            if (sc.PublishedToWeb__c){
                retList.add(sc);
            }
        }
        return retList;
    }
}