force-app/main/default/objects/Contact/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>K - 5</fullName>
            </value>
            <value>
                <fullName>K - 12</fullName>
            </value>
            <value>
                <fullName>1st</fullName>
            </value>
            <value>
                <fullName>2nd</fullName>
            </value>
            <value>
                <fullName>3rd</fullName>
            </value>
            <value>
                <fullName>4th</fullName>
            </value>
            <value>
                <fullName>5th</fullName>
            </value>
            <value>
                <fullName>6th - 8th</fullName>
            </value>
            <value>
                <fullName>9th - 12th</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ProgramType__c.field-meta.xml
<CustomField>
    <fullName>ProgramType__c</fullName>
    <label>Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bilingual Maintenance</fullName>
            </value>
            <value>
                <fullName>Dual Language</fullName>
            </value>
            <value>
                <fullName>Structured English Immersion (most other programs)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Classroom Teacher</fullName>
            </value>
            <value>
                <fullName>Special Education Teacher</fullName>
            </value>
            <value>
                <fullName>Instructional Coach/Specialist</fullName>
            </value>
            <value>
                <fullName>School Site Administrator</fullName>
            </value>
            <value>
                <fullName>District Administrator</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseAttendance__c/CourseAttendance__c.object-meta.xml
<CustomObject>
    <description>Tracks attendance for the students of a course</description>
    <label>Course Attendance</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Attendence Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseAttendance__c/fields/CourseAttendeeEnrollmentId__c.field-meta.xml
<CustomField>
    <fullName>CourseAttendeeEnrollmentId__c</fullName>
    <label>Course Attendee Enrollment</label>
    <referenceTo>CourseEnrollment__c</referenceTo>
    <relationshipLabel>Course Attendance</relationshipLabel>
    <relationshipName>Course_Attendance</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CourseAttendance__c/fields/ScheduledDate__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDate__c</fullName>
    <formula>DATETIMEVALUE( ScheduledCourseDayId__r.ScheduledDate__c )</formula>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CourseEnrollment__c/CourseEnrollment__c.object-meta.xml
<CustomObject>
    <description>Course enrollments for the attendees</description>
    <label>Course Enrollment</label>
    <nameField>
        <displayFormat>E-{0}</displayFormat>
        <label>EnrollmentId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseEnrollment__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>CourseEnrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseEnrollment__c/fields/CoursePaymentInfoId__c.field-meta.xml
<CustomField>
    <fullName>CoursePaymentInfoId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Payment Info</label>
    <referenceTo>CoursePaymentInfo__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>CourseEnrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseEnrollment__c/fields/RegistrationStatus__c.field-meta.xml
<CustomField>
    <fullName>RegistrationStatus__c</fullName>
    <label>Registration Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CourseEnrollment__c/fields/ScheduledCourseId__c.field-meta.xml
<CustomField>
    <fullName>ScheduledCourseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Course</label>
    <referenceTo>ScheduledCourse__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>CourseEnrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CoursePaymentInfo__c/CoursePaymentInfo__c.object-meta.xml
<CustomObject>
    <label>Course Payment Info</label>
    <nameField>
        <displayFormat>CPI-{00000}</displayFormat>
        <label>Course Payment Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Payment Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CoursePaymentInfo__c/fields/AdministratorEmail__c.field-meta.xml
<CustomField>
    <fullName>AdministratorEmail__c</fullName>
    <label>Administrator Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CoursePaymentInfo__c/fields/AdministratorName__c.field-meta.xml
<CustomField>
    <fullName>AdministratorName__c</fullName>
    <label>Administrator Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CoursePaymentInfo__c/fields/InvoiceInfo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceInfo__c</fullName>
    <label>Invoice Info</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CoursePaymentInfo__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Purchase Order</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/ScheduledCourse__c.object-meta.xml
<CustomObject>
    <description>Training schedule for each course</description>
    <label>Scheduled Course</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>SheduledCourseId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduledCourse__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>We can change it to picklist</description>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ControllerRegistrantList.cls
public with sharing class ControllerRegistrantList {
    private String scheduledCourseId {
        get { return getParam('id'); }
    }
    
    public String getParam(String paramName) {
        String param = System.currentPageReference().getParameters().get(paramName);
        if (param == null) return null;
        else return String.escapeSingleQuotes(param);
    }

    public List<String> registrants {
        get {
            if (registrants == null){ 
                registrants = new List<String>();
                List<CourseEnrollment__c> ces = [select Id, ScheduledCourseId__c, ScheduledCourseId__r.Location__c,
                                ContactId__r.FirstName, ContactId__r.LastName, ContactId__r.Email, ContactId__r.Phone, ContactId__r.ProgramType__c,ContactId__r.Grade__c,ContactId__r.Role__c, 
                                ContactId__r.Account.Name, ContactId__r.Account.Website, ContactId__r.Account.BillingStreet, ContactId__r.Account.BillingCity, ContactId__r.Account.BillingState, ContactId__r.Account.BillingPostalCode,
                                CoursePaymentInfoId__r.AdministratorName__c, CoursePaymentInfoId__r.AdministratorEmail__c, CoursePaymentInfoId__r.PaymentMethod__c,CoursePaymentInfoId__r.InvoiceInfo__c,
                                (Select Name, ScheduledDate__c from Course_Attendance__r order by ScheduledDate__c)                 
                                from CourseEnrollment__c 
                                where RegistrationStatus__c = 'Registered' and ScheduledCourseId__c =: scheduledCourseId];
                
               	//first output the csv header labels
               	String hdr = '';
                hdr += getValueForCSV('Status', false); //a
                hdr += getValueForCSV('First Name', false); //b
                hdr += getValueForCSV('Last Name', false); //c
                hdr += getValueForCSV('Phone', false); //d
                hdr += getValueForCSV('Email', false); //e
                hdr += getValueForCSV('Organization', false); //f
                hdr += getValueForCSV('Street', false); //g - h
                hdr += getValueForCSV('City', false); //i
                hdr += getValueForCSV('State', false); //j
                hdr += getValueForCSV('Zip Code', false); //k
                hdr += getValueForCSV('Web Site', false); //l
                hdr += getValueForCSV('District Code', false); //m
                hdr += getValueForCSV('Institution Code', false); //n
                hdr += getValueForCSV('Position', false); //o
                hdr += getValueForCSV('Grade', false); //p
                hdr += getValueForCSV('Program Type', false); //q
                hdr += getValueForCSV('District', false); //r
                hdr += getValueForCSV('Administrator', false); //s
                hdr += getValueForCSV('Admin Email', false); //t
                hdr += getValueForCSV('Location', false); //u
                hdr += getValueForCSV('Dates', false); //v

                Integer d = 1;
                for (CourseAttendance__c day : ces[0].Course_Attendance__r){
                    hdr += getValueForCSV('Day ' + d, false); //w - ab
                    d++;
                }

                hdr += getValueForCSV('Certified', false); //ac
                hdr += getValueForCSV('Notes', false); //ad
                hdr += getValueForCSV('Invoice #', false); //ae
                hdr += getValueForCSV('Payment Method', true); //af
                
                registrants.add(hdr);
                
                // second add items for each registrant
                for (CourseEnrollment__c ce : ces){
                    String s = '';
                    s += getValueForCSV('', false); //a
                    s += getValueForCSV(ce.ContactId__r.FirstName, false); //b
                    s += getValueForCSV(ce.ContactId__r.LastName, false); //c
                    s += getValueForCSV(ce.ContactId__r.Phone, false); //d                    
                    s += getValueForCSV(ce.ContactId__r.Email, false); //e
                    s += getValueForCSV(ce.ContactId__r.Account.Name, false); //f
                    s += getValueForCSV(ce.ContactId__r.Account.BillingStreet, false); //g- h
                    s += getValueForCSV(ce.ContactId__r.Account.BillingCity, false); //i
                    s += getValueForCSV(ce.ContactId__r.Account.BillingState, false); //j
                    s += getValueForCSV(ce.ContactId__r.Account.BillingPostalCode, false); //k
                    s += getValueForCSV(ce.ContactId__r.Account.Website, false); //l
                    s += getValueForCSV('', false); //m
                    s += getValueForCSV('', false); //n
                    s += getValueForCSV(ce.ContactId__r.Role__c, false); //o
                    s += getValueForCSV(ce.ContactId__r.Grade__c, false); //p
                    s += getValueForCSV(ce.ContactId__r.ProgramType__c, false); //q
                    s += getValueForCSV('', false); //r
                    s += getValueForCSV(ce.CoursePaymentInfoId__r.AdministratorName__c, false); //s
                    s += getValueForCSV(ce.CoursePaymentInfoId__r.AdministratorEmail__c, false); //t
                    s += getValueForCSV(ce.ScheduledCourseId__r.Location__c, false); //u
                    s += getValueForCSV('Dates', false); //v

                    for (CourseAttendance__c day : ce.Course_Attendance__r){
                        s += getValueForCSV('', false); //w - ab
                    }
                    
                    s += getValueForCSV('', false); //ac
                    s += getValueForCSV('', false); //ad
                    s += getValueForCSV(ce.CoursePaymentInfoId__r.InvoiceInfo__c, false); //ae
                    s += getValueForCSV(ce.CoursePaymentInfoId__r.PaymentMethod__c, true); //af    
                    
                    registrants.add(s);
                }
            }
            return registrants;
        }
        private set;
    }
    
    private String getValueForCSV(String s, Boolean lastValue){
		String v = (String.isEmpty(s)) ? '' : s;
        String r = '"' + v.replace('"','""') + '"';
        if (!lastValue){
            r += ',';
        }
        return r;
    }
}