force-app/main/default/objects/CourseAttendance__c/CourseAttendance__c.object-meta.xml
<CustomObject>
    <description>Tracks attendance for the students of a course</description>
    <label>Course Attendance</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Attendence Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseAttendance__c/fields/AttendanceNotes__c.field-meta.xml
<CustomField>
    <fullName>AttendanceNotes__c</fullName>
    <label>Attendance Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CourseAttendance__c/fields/Attended__c.field-meta.xml
<CustomField>
    <fullName>Attended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CourseAttendance__c/fields/CourseAttendeeEnrollmentId__c.field-meta.xml
<CustomField>
    <fullName>CourseAttendeeEnrollmentId__c</fullName>
    <label>Course Attendee Enrollment</label>
    <referenceTo>CourseEnrollment__c</referenceTo>
    <relationshipLabel>Course Attendance</relationshipLabel>
    <relationshipName>Course_Attendance</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CourseEnrollment__c/CourseEnrollment__c.object-meta.xml
<CustomObject>
    <description>Course enrollments for the attendees</description>
    <label>Course Enrollment</label>
    <nameField>
        <displayFormat>E-{0}</displayFormat>
        <label>EnrollmentId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseEnrollment__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>CourseEnrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseEnrollment__c/fields/LeadId__c.field-meta.xml
<CustomField>
    <fullName>LeadId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>CourseEnrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseEnrollment__c/fields/RegistrationStatus__c.field-meta.xml
<CustomField>
    <fullName>RegistrationStatus__c</fullName>
    <label>Registration Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Attendee.cls
public class Attendee {
    public String Id {get;set;}
    public String Name {get;set;}
    public String Email {get;set;}
    public String Status {get;set;}
    public String Notes {get;set;}
    public String Attended {get;set;}

    public Attendee(CourseAttendance__c ca){
        this.Id = ca.Id;

        this.Status = ca.CourseAttendeeEnrollmentId__r.RegistrationStatus__c;
        this.Notes = ca.AttendanceNotes__c;
        this.Attended =  String.valueOf(ca.Attended__c);

        // use contact info if we have it
        if (ca.CourseAttendeeEnrollmentId__r.ContactId__c != null) {
            this.Name = ca.CourseAttendeeEnrollmentId__r.ContactId__r.Name;
            this.Email = ca.CourseAttendeeEnrollmentId__r.ContactId__r.Email;
        } else {
            this.Name = ca.CourseAttendeeEnrollmentId__r.LeadId__r.Name;
            this.Email = ca.CourseAttendeeEnrollmentId__r.LeadId__r.Email;
        }
    }
}