force-app/main/default/objects/ProjectFacilitator__c/ProjectFacilitator__c.object-meta.xml
<CustomObject>
    <label>Project Facilitator</label>
    <nameField>
        <label>Project Facilitator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Facilitators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectFacilitator__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectSupporter__c/ProjectSupporter__c.object-meta.xml
<CustomObject>
    <label>Project Supporter</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Project Supporter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Supporters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectSupporter__c/fields/ProjectFacilitator__c.field-meta.xml
<CustomField>
    <fullName>ProjectFacilitator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Facilitator</label>
    <referenceTo>ProjectFacilitator__c</referenceTo>
    <relationshipLabel>Project Supporters</relationshipLabel>
    <relationshipName>Project_Supporters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectSupporter__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Project Supporters</relationshipLabel>
    <relationshipName>Project_Supporters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PrimaryFacilitator__c.field-meta.xml
<CustomField>
    <fullName>PrimaryFacilitator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Facilitator</label>
    <referenceTo>ProjectFacilitator__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestQuoteTriggerHandler.cls
@isTest(seealldata=true)
public class TestQuoteTriggerHandler {

    @isTest
    public static void testQuote() {
        Account a = new Account();
        a.Name = 'Test Account';
        insert a;
        
        RecordType rt = [select Id, Name from RecordType where Name = 'Training Sales'];
        
        Opportunity o = new Opportunity();
        o.AccountId = a.Id;
        o.RecordTypeId = rt.Id;
        o.StageName = 'Planning';
        o.Name = 'Test Oppty';
        o.CloseDate = Date.today();
        insert o;
        
        Pricebook2 pb = [select Id from Pricebook2 where Name = 'DLENM - PD'];
        
        User u = [select Id from User where IsActive = true limit 1];
        
        User u2 = [select Id from User where IsActive = true and Id <>: u.Id limit 1];
        
        ProjectFacilitator__c pf = new ProjectFacilitator__c();
        pf.Name = 'Test Test';
        pf.Type__c = 'Staff';
        insert pf;
        
        Quote q = new Quote();
        q.Name = 'Test Quote';
        q.OpportunityId = o.Id;
        q.Pricebook2Id = pb.Id;
        q.PrimaryFacilitator__c = pf.Id;
        insert q;
        
        ProjectSupporter__c ps = new ProjectSupporter__c();
        ps.ProjectFacilitator__c = pf.Id;
        ps.Quote__c = q.Id;
        insert ps;
        
        PricebookEntry pbe = [select Id from PricebookEntry where Pricebook2Id =: pb.Id order by CreatedDate desc limit 1];
    
        QuoteLineItem ql = new QuoteLineItem();
        ql.QuoteId = q.Id;
        ql.PricebookEntryId = pbe.Id;
        ql.Quantity = 1;
        ql.UnitPrice = 1.00;
        ql.ServiceDate = Date.today().addDays(5);
        insert ql;
        
        Test.startTest();
        
        q.Status = 'Approved';
        update q;
        
        q.Status = 'Draft';
        update q;
                
        ql.ServiceDate = Date.today().addDays(10);
        update ql;
        
        q.Status = 'Approved';
        update q;
        
        q.Status = 'Accepted';
        update q;
        
        Test.stopTest();
    }
    
}